export const GEOLOCATION_API_URL = process.env.NEXT_PUBLIC_GEOLOCATION_API_ENDPOINT || ''
export const GEOLOCATION_API_KEY = process.env.GEOLOCATION_API_KEY || ''
export const GEOLOCATION_CACHE_LIFETIME = 60