import { ReactElement } from 'react'
import Head from 'next/head'
import { SWRConfig, unstable_serialize } from 'swr'
import {
  Container,
  // Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'

import Main from '../components/pages/main'
import { GetServerSideProps } from 'next'
import { cookies } from 'next/dist/client/components/headers'
import BaseLayout from '../components/layouts/baseLayout'
import { getUserLocationServer } from '../services/queries/server/getUserLocationServer'
import { GeolocationApiResponse } from '../types/geolocationApi'


export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  console.log('SSR index.tsx')

  const fields = []
  let data: Partial<GeolocationApiResponse> | null

  try {
    const userLocation = await getUserLocationServer(fields)
    data = userLocation
    console.log('data: ', data)
  } catch(error) {
    console.log(error)
    data = null
  }

  return {
    props: {
      fallback: {
        [unstable_serialize(fields)]: data,
      },
    },
  }
}


type PageProps = {
  fallback: {
    [key: string]: any
  }
}

// TODO: global error handling

const Home = ({ fallback }: PageProps) => {
  return (
    <SWRConfig value={{fallback}}>
      <Main />
    </SWRConfig>
    // <Container>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Main>
    //     <Title>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </Title>

    //     <Description>
    //       Get started by editing
    //       <CodeTag>pages/index.tsx</CodeTag>
    //     </Description>

    //     <Cards />
    //   </Main>
    // </Container>
  )
}

Home.getLayout = (page: ReactElement) => (
  <BaseLayout>{page}</BaseLayout>
)

export default Home
